-- 3. Foreign Keys

ALTER TABLE activity_logs ADD CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE activity_logs ADD CONSTRAINT activity_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES admins (id);
ALTER TABLE admins ADD CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE advertising_campaigns ADD CONSTRAINT advertising_campaigns_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id);
ALTER TABLE advertising_credits ADD CONSTRAINT advertising_credits_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE advertising_impressions ADD CONSTRAINT advertising_impressions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE advertising_impressions ADD CONSTRAINT advertising_impressions_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE;
ALTER TABLE advertising_impressions ADD CONSTRAINT advertising_impressions_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES advertising_subscriptions (id) ON DELETE CASCADE;
ALTER TABLE advertising_payments ADD CONSTRAINT advertising_payments_tax_invoice_id_fkey FOREIGN KEY (tax_invoice_id) REFERENCES tax_invoices (id);
ALTER TABLE advertising_payments ADD CONSTRAINT advertising_payments_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES sellers (id) ON DELETE CASCADE;
ALTER TABLE advertising_payments ADD CONSTRAINT advertising_payments_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES admins (id);
ALTER TABLE advertising_payments ADD CONSTRAINT advertising_payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES advertising_subscriptions (id) ON DELETE CASCADE;
ALTER TABLE advertising_subscriptions ADD CONSTRAINT advertising_subscriptions_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE;
ALTER TABLE advertising_subscriptions ADD CONSTRAINT advertising_subscriptions_bank_transfer_confirmed_by_fkey FOREIGN KEY (bank_transfer_confirmed_by) REFERENCES admins (id);
ALTER TABLE advertising_subscriptions ADD CONSTRAINT advertising_subscriptions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES sellers (id) ON DELETE CASCADE;
ALTER TABLE categories ADD CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES categories (id);
ALTER TABLE chat_favorites ADD CONSTRAINT chat_favorites_room_id_fkey FOREIGN KEY (room_id) REFERENCES chat_rooms (id) ON DELETE CASCADE;
ALTER TABLE chat_rooms ADD CONSTRAINT chat_rooms_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE SET NULL;
ALTER TABLE conversations ADD CONSTRAINT conversations_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE conversations ADD CONSTRAINT conversations_participant1_id_fkey FOREIGN KEY (participant1_id) REFERENCES users (id);
ALTER TABLE conversations ADD CONSTRAINT conversations_participant2_id_fkey FOREIGN KEY (participant2_id) REFERENCES users (id);
ALTER TABLE credit_transactions ADD CONSTRAINT credit_transactions_credit_id_fkey FOREIGN KEY (credit_id) REFERENCES advertising_credits (id) ON DELETE CASCADE;
ALTER TABLE credit_transactions ADD CONSTRAINT credit_transactions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE disputes ADD CONSTRAINT disputes_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE disputes ADD CONSTRAINT disputes_mediator_id_fkey FOREIGN KEY (mediator_id) REFERENCES admins (id);
ALTER TABLE disputes ADD CONSTRAINT disputes_initiated_by_fkey FOREIGN KEY (initiated_by) REFERENCES users (id);
ALTER TABLE earnings_transactions ADD CONSTRAINT earnings_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE earnings_transactions ADD CONSTRAINT earnings_transactions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE errand_applications ADD CONSTRAINT errand_applications_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES profiles (id) ON DELETE CASCADE;
ALTER TABLE errand_applications ADD CONSTRAINT errand_applications_errand_id_fkey FOREIGN KEY (errand_id) REFERENCES errands (id) ON DELETE CASCADE;
ALTER TABLE errand_chat_messages ADD CONSTRAINT errand_chat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles (id) ON DELETE CASCADE;
ALTER TABLE errand_chat_messages ADD CONSTRAINT errand_chat_messages_errand_id_fkey FOREIGN KEY (errand_id) REFERENCES errands (id) ON DELETE CASCADE;
ALTER TABLE errand_disputes ADD CONSTRAINT errand_disputes_reported_id_fkey FOREIGN KEY (reported_id) REFERENCES profiles (id) ON DELETE CASCADE;
ALTER TABLE errand_disputes ADD CONSTRAINT errand_disputes_errand_id_fkey FOREIGN KEY (errand_id) REFERENCES errands (id) ON DELETE CASCADE;
ALTER TABLE errand_disputes ADD CONSTRAINT errand_disputes_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES profiles (id) ON DELETE CASCADE;
ALTER TABLE errand_disputes ADD CONSTRAINT errand_disputes_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES profiles (id);
ALTER TABLE errand_locations ADD CONSTRAINT errand_locations_errand_id_fkey FOREIGN KEY (errand_id) REFERENCES errands (id) ON DELETE CASCADE;
ALTER TABLE errand_locations ADD CONSTRAINT errand_locations_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES profiles (id) ON DELETE CASCADE;
ALTER TABLE errand_messages ADD CONSTRAINT errand_messages_errand_id_fkey FOREIGN KEY (errand_id) REFERENCES errands (id) ON DELETE CASCADE;
ALTER TABLE errand_messages ADD CONSTRAINT errand_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles (id) ON DELETE CASCADE;
ALTER TABLE errand_reviews ADD CONSTRAINT errand_reviews_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES helper_profiles (id) ON DELETE CASCADE;
ALTER TABLE errand_reviews ADD CONSTRAINT errand_reviews_errand_id_fkey FOREIGN KEY (errand_id) REFERENCES errands (id) ON DELETE CASCADE;
ALTER TABLE errand_reviews ADD CONSTRAINT errand_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES profiles (id) ON DELETE CASCADE;
ALTER TABLE errand_settlements ADD CONSTRAINT errand_settlements_errand_id_fkey FOREIGN KEY (errand_id) REFERENCES errands (id) ON DELETE CASCADE;
ALTER TABLE errand_settlements ADD CONSTRAINT errand_settlements_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES helper_profiles (id) ON DELETE CASCADE;
ALTER TABLE errand_stops ADD CONSTRAINT errand_stops_errand_id_fkey FOREIGN KEY (errand_id) REFERENCES errands (id) ON DELETE CASCADE;
ALTER TABLE errands ADD CONSTRAINT errands_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES profiles (id) ON DELETE SET NULL;
ALTER TABLE errands ADD CONSTRAINT errands_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES profiles (id) ON DELETE CASCADE;
ALTER TABLE food_carts ADD CONSTRAINT food_carts_store_id_fkey FOREIGN KEY (store_id) REFERENCES food_stores (id) ON DELETE CASCADE;
ALTER TABLE food_menu_categories ADD CONSTRAINT food_menu_categories_store_id_fkey FOREIGN KEY (store_id) REFERENCES food_stores (id) ON DELETE CASCADE;
ALTER TABLE food_menu_option_groups ADD CONSTRAINT food_menu_option_groups_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES food_menus (id) ON DELETE CASCADE;
ALTER TABLE food_menu_option_items ADD CONSTRAINT food_menu_option_items_option_group_id_fkey FOREIGN KEY (option_group_id) REFERENCES food_menu_option_groups (id) ON DELETE CASCADE;
ALTER TABLE food_menus ADD CONSTRAINT food_menus_store_id_fkey FOREIGN KEY (store_id) REFERENCES food_stores (id) ON DELETE CASCADE;
ALTER TABLE food_menus ADD CONSTRAINT food_menus_category_id_fkey FOREIGN KEY (category_id) REFERENCES food_menu_categories (id) ON DELETE SET NULL;
ALTER TABLE food_orders ADD CONSTRAINT food_orders_store_id_fkey FOREIGN KEY (store_id) REFERENCES food_stores (id);
ALTER TABLE food_reviews ADD CONSTRAINT food_reviews_store_id_fkey FOREIGN KEY (store_id) REFERENCES food_stores (id) ON DELETE CASCADE;
ALTER TABLE food_reviews ADD CONSTRAINT food_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES food_orders (id);
ALTER TABLE food_store_favorites ADD CONSTRAINT food_store_favorites_store_id_fkey FOREIGN KEY (store_id) REFERENCES food_stores (id) ON DELETE CASCADE;
ALTER TABLE helper_subscriptions ADD CONSTRAINT helper_subscriptions_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES helper_profiles (id) ON DELETE CASCADE;
ALTER TABLE helper_withdrawals ADD CONSTRAINT helper_withdrawals_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES profiles (id);
ALTER TABLE helper_withdrawals ADD CONSTRAINT helper_withdrawals_helper_id_fkey FOREIGN KEY (helper_id) REFERENCES helper_profiles (id) ON DELETE CASCADE;
ALTER TABLE messages ADD CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES users (id);
ALTER TABLE messages ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT notifications_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE order_settlements ADD CONSTRAINT order_settlements_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE order_settlements ADD CONSTRAINT order_settlements_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE order_settlements ADD CONSTRAINT order_settlements_batch_settlement_id_fkey FOREIGN KEY (batch_settlement_id) REFERENCES settlements (id);
ALTER TABLE orders ADD CONSTRAINT orders_review_id_fkey FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE SET NULL;
ALTER TABLE orders ADD CONSTRAINT orders_payment_request_id_fkey FOREIGN KEY (payment_request_id) REFERENCES payment_requests (id) ON DELETE SET NULL;
ALTER TABLE orders ADD CONSTRAINT orders_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id);
ALTER TABLE orders ADD CONSTRAINT orders_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES users (id);
ALTER TABLE orders ADD CONSTRAINT orders_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE SET NULL;
ALTER TABLE payment_requests ADD CONSTRAINT payment_requests_room_id_fkey FOREIGN KEY (room_id) REFERENCES chat_rooms (id) ON DELETE CASCADE;
ALTER TABLE payment_requests ADD CONSTRAINT payment_requests_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE SET NULL;
ALTER TABLE payment_requests ADD CONSTRAINT payment_requests_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE payment_requests ADD CONSTRAINT payment_requests_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES sellers (id) ON DELETE CASCADE;
ALTER TABLE payments ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE portfolio_items ADD CONSTRAINT portfolio_items_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE portfolio_services ADD CONSTRAINT portfolio_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE;
ALTER TABLE portfolio_services ADD CONSTRAINT portfolio_services_portfolio_id_fkey FOREIGN KEY (portfolio_id) REFERENCES seller_portfolio (id) ON DELETE CASCADE;
ALTER TABLE premium_placements ADD CONSTRAINT premium_placements_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id);
ALTER TABLE premium_placements ADD CONSTRAINT premium_placements_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL;
ALTER TABLE premium_placements ADD CONSTRAINT premium_placements_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES advertising_campaigns (id) ON DELETE CASCADE;
ALTER TABLE quote_responses ADD CONSTRAINT quote_responses_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE CASCADE;
ALTER TABLE quote_responses ADD CONSTRAINT quote_responses_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE quotes ADD CONSTRAINT quotes_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL;
ALTER TABLE quotes ADD CONSTRAINT quotes_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE refunds ADD CONSTRAINT refunds_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE refunds ADD CONSTRAINT refunds_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE CASCADE;
ALTER TABLE refunds ADD CONSTRAINT refunds_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE reports ADD CONSTRAINT reports_reported_review_id_fkey FOREIGN KEY (reported_review_id) REFERENCES reviews (id);
ALTER TABLE reports ADD CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES users (id);
ALTER TABLE reports ADD CONSTRAINT reports_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES admins (id);
ALTER TABLE reports ADD CONSTRAINT reports_reported_order_id_fkey FOREIGN KEY (reported_order_id) REFERENCES orders (id);
ALTER TABLE reports ADD CONSTRAINT reports_reported_service_id_fkey FOREIGN KEY (reported_service_id) REFERENCES services (id);
ALTER TABLE reports ADD CONSTRAINT reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES users (id);
ALTER TABLE reviews ADD CONSTRAINT reviews_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE SET NULL;
ALTER TABLE reviews ADD CONSTRAINT reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE reviews ADD CONSTRAINT reviews_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id);
ALTER TABLE reviews ADD CONSTRAINT reviews_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES users (id);
ALTER TABLE revision_history ADD CONSTRAINT revision_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE search_logs ADD CONSTRAINT search_logs_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL;
ALTER TABLE search_logs ADD CONSTRAINT search_logs_converted_service_id_fkey FOREIGN KEY (converted_service_id) REFERENCES services (id);
ALTER TABLE search_logs ADD CONSTRAINT search_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE seller_earnings ADD CONSTRAINT seller_earnings_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE seller_portfolio ADD CONSTRAINT seller_portfolio_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL;
ALTER TABLE seller_portfolio ADD CONSTRAINT seller_portfolio_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE SET NULL;
ALTER TABLE seller_portfolio ADD CONSTRAINT seller_portfolio_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES sellers (id) ON DELETE CASCADE;
ALTER TABLE service_categories ADD CONSTRAINT service_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE;
ALTER TABLE service_categories ADD CONSTRAINT service_categories_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE;
ALTER TABLE service_favorites ADD CONSTRAINT service_favorites_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE;
ALTER TABLE service_packages ADD CONSTRAINT service_packages_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE;
ALTER TABLE service_revision_categories ADD CONSTRAINT service_revision_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE;
ALTER TABLE service_revision_categories ADD CONSTRAINT service_revision_categories_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES service_revisions (id) ON DELETE CASCADE;
ALTER TABLE service_revisions ADD CONSTRAINT service_revisions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES sellers (id) ON DELETE CASCADE;
ALTER TABLE service_revisions ADD CONSTRAINT service_revisions_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE;
ALTER TABLE service_tags ADD CONSTRAINT service_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE;
ALTER TABLE service_tags ADD CONSTRAINT service_tags_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE;
ALTER TABLE service_view_logs ADD CONSTRAINT service_view_logs_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE;
ALTER TABLE service_views ADD CONSTRAINT service_views_service_id_fkey FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE;
ALTER TABLE services ADD CONSTRAINT services_last_modified_by_fkey FOREIGN KEY (last_modified_by) REFERENCES users (id);
ALTER TABLE services ADD CONSTRAINT services_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES sellers (id) ON DELETE CASCADE;
ALTER TABLE settlement_details ADD CONSTRAINT settlement_details_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE settlement_details ADD CONSTRAINT settlement_details_settlement_id_fkey FOREIGN KEY (settlement_id) REFERENCES settlements (id) ON DELETE CASCADE;
ALTER TABLE settlements ADD CONSTRAINT settlements_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES users (id);
ALTER TABLE tax_invoices ADD CONSTRAINT tax_invoices_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES advertising_subscriptions (id);
ALTER TABLE tax_invoices ADD CONSTRAINT tax_invoices_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES advertising_payments (id);
ALTER TABLE user_wallets ADD CONSTRAINT user_wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE wallet_transactions ADD CONSTRAINT wallet_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE wallet_transactions ADD CONSTRAINT wallet_transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES user_wallets (id) ON DELETE CASCADE;
ALTER TABLE wallet_transactions ADD CONSTRAINT wallet_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE withdrawal_requests ADD CONSTRAINT withdrawal_requests_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES sellers (id) ON DELETE CASCADE;
ALTER TABLE withdrawal_requests ADD CONSTRAINT withdrawal_requests_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES users (id);
