-- 4. Indexes

CREATE INDEX idx_activity_logs_admin_id ON public.activity_logs USING btree (admin_id);
CREATE INDEX idx_activity_logs_user_id ON public.activity_logs USING btree (user_id);
CREATE UNIQUE INDEX admins_user_id_key ON public.admins USING btree (user_id);
CREATE INDEX idx_campaigns_seller ON public.advertising_campaigns USING btree (seller_id);
CREATE INDEX idx_campaigns_status ON public.advertising_campaigns USING btree (status, approval_status);
CREATE INDEX idx_advertising_credits_expires_at ON public.advertising_credits USING btree (expires_at);
CREATE INDEX idx_advertising_credits_seller_id ON public.advertising_credits USING btree (seller_id);
CREATE INDEX idx_ad_impressions_category_id ON public.advertising_impressions USING btree (category_id);
CREATE INDEX idx_ad_impressions_clicked ON public.advertising_impressions USING btree (clicked) WHERE (clicked = true);
CREATE INDEX idx_ad_impressions_created_at ON public.advertising_impressions USING btree (created_at);
CREATE INDEX idx_ad_impressions_service_id ON public.advertising_impressions USING btree (service_id);
CREATE INDEX idx_ad_impressions_subscription_id ON public.advertising_impressions USING btree (subscription_id);
CREATE INDEX idx_ad_payments_created_at ON public.advertising_payments USING btree (created_at);
CREATE INDEX idx_ad_payments_payment_method ON public.advertising_payments USING btree (payment_method);
CREATE INDEX idx_ad_payments_seller_id ON public.advertising_payments USING btree (seller_id);
CREATE INDEX idx_ad_payments_status ON public.advertising_payments USING btree (status);
CREATE INDEX idx_ad_payments_subscription_id ON public.advertising_payments USING btree (subscription_id);
CREATE UNIQUE INDEX advertising_subscriptions_service_id_key ON public.advertising_subscriptions USING btree (service_id);
CREATE INDEX idx_ad_subscriptions_bank_transfer ON public.advertising_subscriptions USING btree (bank_transfer_confirmed) WHERE (payment_method = 'bank_transfer'::text);
CREATE INDEX idx_ad_subscriptions_next_billing ON public.advertising_subscriptions USING btree (next_billing_date);
CREATE INDEX idx_ad_subscriptions_seller_id ON public.advertising_subscriptions USING btree (seller_id);
CREATE INDEX idx_ad_subscriptions_service_id ON public.advertising_subscriptions USING btree (service_id);
CREATE INDEX idx_ad_subscriptions_status ON public.advertising_subscriptions USING btree (status);
CREATE INDEX buyers_user_id_idx ON public.buyers USING btree (user_id);
CREATE UNIQUE INDEX buyers_user_id_key ON public.buyers USING btree (user_id);
CREATE INDEX idx_buyers_created_at ON public.buyers USING btree (created_at DESC);
CREATE INDEX idx_buyers_is_active ON public.buyers USING btree (is_active);
CREATE UNIQUE INDEX categories_slug_key ON public.categories USING btree (slug);
CREATE INDEX idx_categories_active ON public.categories USING btree (is_active, display_order);
CREATE INDEX idx_categories_ai ON public.categories USING btree (is_ai_category, is_active);
CREATE INDEX idx_categories_is_ai ON public.categories USING btree (is_ai) WHERE (is_ai = true);
CREATE INDEX idx_categories_keywords ON public.categories USING gin (keywords);
CREATE INDEX idx_categories_level ON public.categories USING btree (level);
CREATE INDEX idx_categories_parent ON public.categories USING btree (parent_id);
CREATE INDEX idx_categories_parent_id ON public.categories USING btree (parent_id, display_order);
CREATE INDEX idx_categories_popularity ON public.categories USING btree (popularity_score DESC);
CREATE INDEX idx_categories_root ON public.categories USING btree (display_order) WHERE ((parent_id IS NULL) AND (is_active = true));
CREATE INDEX idx_categories_service_count ON public.categories USING btree (service_count DESC);
CREATE INDEX idx_categories_slug ON public.categories USING btree (slug);
CREATE INDEX idx_category_visits_category_id ON public.category_visits USING btree (category_id);
CREATE INDEX idx_category_visits_cleanup ON public.category_visits USING btree (visited_at);
CREATE UNIQUE INDEX idx_category_visits_unique_daily ON public.category_visits USING btree (user_id, category_id, visited_date);
CREATE INDEX idx_category_visits_user_date ON public.category_visits USING btree (user_id, visited_at DESC);
CREATE INDEX idx_category_visits_user_id ON public.category_visits USING btree (user_id);
CREATE INDEX idx_category_visits_visited_at ON public.category_visits USING btree (visited_at DESC);
CREATE UNIQUE INDEX chat_favorites_user_id_room_id_key ON public.chat_favorites USING btree (user_id, room_id);
CREATE INDEX idx_chat_favorites_room_id ON public.chat_favorites USING btree (room_id);
CREATE INDEX idx_chat_favorites_user_id ON public.chat_favorites USING btree (user_id);
CREATE INDEX idx_chat_messages_created_at ON public.chat_messages USING btree (created_at DESC);
CREATE INDEX idx_chat_messages_room_created ON public.chat_messages USING btree (room_id, created_at DESC);
CREATE INDEX idx_chat_messages_room_id ON public.chat_messages USING btree (room_id);
CREATE INDEX idx_chat_messages_room_sender ON public.chat_messages USING btree (room_id, sender_id);
CREATE INDEX idx_chat_messages_sender ON public.chat_messages USING btree (sender_id);
CREATE INDEX idx_chat_messages_unread ON public.chat_messages USING btree (room_id, is_read, sender_id) WHERE (is_read = false);
CREATE UNIQUE INDEX chat_rooms_users_service_unique ON public.chat_rooms USING btree (user1_id, user2_id, service_id) NULLS NOT DISTINCT;
CREATE INDEX idx_chat_rooms_last_message_at ON public.chat_rooms USING btree (last_message_at DESC);
CREATE INDEX idx_chat_rooms_service_id ON public.chat_rooms USING btree (service_id) WHERE (service_id IS NOT NULL);
CREATE INDEX idx_chat_rooms_user1_id ON public.chat_rooms USING btree (user1_id);
CREATE INDEX idx_chat_rooms_user1_last_message ON public.chat_rooms USING btree (user1_id, last_message_at DESC);
CREATE INDEX idx_chat_rooms_user2_id ON public.chat_rooms USING btree (user2_id);
CREATE INDEX idx_chat_rooms_user2_last_message ON public.chat_rooms USING btree (user2_id, last_message_at DESC);
CREATE UNIQUE INDEX company_info_business_number_key ON public.company_info USING btree (business_number);
CREATE INDEX idx_conversations_order_id ON public.conversations USING btree (order_id);
CREATE INDEX idx_conversations_participants ON public.conversations USING btree (participant1_id, participant2_id);
CREATE INDEX idx_credit_transactions_created_at ON public.credit_transactions USING btree (created_at);
CREATE INDEX idx_credit_transactions_credit_id ON public.credit_transactions USING btree (credit_id);
CREATE INDEX idx_credit_transactions_seller_id ON public.credit_transactions USING btree (seller_id);
CREATE INDEX idx_credit_transactions_type ON public.credit_transactions USING btree (transaction_type);
CREATE INDEX idx_disputes_initiated_by ON public.disputes USING btree (initiated_by);
CREATE INDEX idx_disputes_mediator_id ON public.disputes USING btree (mediator_id);
CREATE INDEX idx_disputes_order_id ON public.disputes USING btree (order_id);
CREATE INDEX idx_earnings_transactions_date ON public.earnings_transactions USING btree (transaction_date DESC);
CREATE INDEX idx_earnings_transactions_order_id ON public.earnings_transactions USING btree (order_id);
CREATE INDEX idx_earnings_transactions_seller_id ON public.earnings_transactions USING btree (seller_id);
CREATE INDEX idx_earnings_transactions_status ON public.earnings_transactions USING btree (status);
CREATE UNIQUE INDEX errand_applications_errand_id_helper_id_key ON public.errand_applications USING btree (errand_id, helper_id);
CREATE INDEX idx_errand_applications_errand ON public.errand_applications USING btree (errand_id);
CREATE INDEX idx_errand_applications_helper ON public.errand_applications USING btree (helper_id);
CREATE INDEX idx_errand_chat_messages_created_at ON public.errand_chat_messages USING btree (created_at DESC);
CREATE INDEX idx_errand_chat_messages_errand_id ON public.errand_chat_messages USING btree (errand_id);
CREATE INDEX idx_errand_chat_messages_sender_id ON public.errand_chat_messages USING btree (sender_id);
CREATE INDEX idx_errand_disputes_status ON public.errand_disputes USING btree (status);
CREATE INDEX idx_errand_locations_errand ON public.errand_locations USING btree (errand_id);
CREATE INDEX idx_errand_messages_errand ON public.errand_messages USING btree (errand_id);
CREATE UNIQUE INDEX errand_reviews_errand_id_key ON public.errand_reviews USING btree (errand_id);
CREATE INDEX idx_errand_reviews_helper ON public.errand_reviews USING btree (helper_id);
CREATE UNIQUE INDEX errand_settlements_errand_id_key ON public.errand_settlements USING btree (errand_id);
CREATE INDEX idx_errand_settlements_helper ON public.errand_settlements USING btree (helper_id);
CREATE INDEX idx_errand_settlements_status ON public.errand_settlements USING btree (status);
CREATE INDEX idx_errands_category ON public.errands USING btree (category);
CREATE INDEX idx_errands_created ON public.errands USING btree (created_at DESC);
CREATE INDEX idx_errands_helper ON public.errands USING btree (helper_id);
CREATE INDEX idx_errands_requester ON public.errands USING btree (requester_id);
CREATE INDEX idx_errands_status ON public.errands USING btree (status);
CREATE UNIQUE INDEX food_carts_user_id_store_id_key ON public.food_carts USING btree (user_id, store_id);
CREATE INDEX idx_food_menus_store ON public.food_menus USING btree (store_id);
CREATE UNIQUE INDEX food_orders_order_number_key ON public.food_orders USING btree (order_number);
CREATE INDEX idx_food_orders_customer ON public.food_orders USING btree (customer_id);
CREATE INDEX idx_food_orders_status ON public.food_orders USING btree (status);
CREATE INDEX idx_food_orders_store ON public.food_orders USING btree (store_id);
CREATE INDEX idx_food_reviews_store ON public.food_reviews USING btree (store_id);
CREATE UNIQUE INDEX food_store_favorites_user_id_store_id_key ON public.food_store_favorites USING btree (user_id, store_id);
CREATE INDEX idx_food_stores_active ON public.food_stores USING btree (is_active, is_verified);
CREATE INDEX idx_food_stores_category ON public.food_stores USING btree (category);
CREATE INDEX idx_food_stores_location ON public.food_stores USING btree (latitude, longitude);
CREATE UNIQUE INDEX helper_profiles_user_id_key ON public.helper_profiles USING btree (user_id);
CREATE INDEX idx_helper_profiles_grade ON public.helper_profiles USING btree (grade);
CREATE INDEX idx_helper_profiles_location ON public.helper_profiles USING btree (current_lat, current_lng) WHERE ((is_online = true) AND (is_active = true));
CREATE INDEX idx_helper_profiles_online_active ON public.helper_profiles USING btree (is_online, is_active, last_location_at) WHERE ((is_online = true) AND (is_active = true));
CREATE INDEX idx_helper_profiles_status ON public.helper_profiles USING btree (subscription_status);
CREATE INDEX idx_helper_profiles_user ON public.helper_profiles USING btree (user_id);
CREATE INDEX idx_helper_subscriptions_helper ON public.helper_subscriptions USING btree (helper_id);
CREATE INDEX idx_helper_withdrawals_helper ON public.helper_withdrawals USING btree (helper_id);
CREATE INDEX idx_helper_withdrawals_status ON public.helper_withdrawals USING btree (status);
CREATE INDEX idx_messages_conversation ON public.messages USING btree (conversation_id);
CREATE INDEX idx_messages_sender ON public.messages USING btree (sender_id);
CREATE INDEX idx_notices_category ON public.notices USING btree (category);
CREATE INDEX idx_notices_created_at ON public.notices USING btree (created_at DESC);
CREATE INDEX idx_notices_is_important ON public.notices USING btree (is_important);
CREATE INDEX idx_notices_is_published ON public.notices USING btree (is_published);
CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at DESC);
CREATE INDEX idx_notifications_order_id ON public.notifications USING btree (order_id) WHERE (order_id IS NOT NULL);
CREATE INDEX idx_notifications_user_id ON public.notifications USING btree (user_id);
CREATE INDEX idx_notifications_user_unread ON public.notifications USING btree (user_id, is_read) WHERE (is_read = false);
CREATE INDEX idx_order_settlements_confirmed_at ON public.order_settlements USING btree (confirmed_at) WHERE ((status)::text = 'confirmed'::text);
CREATE INDEX idx_order_settlements_order_id ON public.order_settlements USING btree (order_id);
CREATE INDEX idx_order_settlements_seller_id ON public.order_settlements USING btree (seller_id);
CREATE INDEX idx_order_settlements_status ON public.order_settlements USING btree (status);
CREATE INDEX idx_orders_buyer ON public.orders USING btree (buyer_id);
CREATE INDEX idx_orders_buyer_id ON public.orders USING btree (buyer_id, created_at DESC);
CREATE INDEX idx_orders_buyer_status ON public.orders USING btree (buyer_id, status) WHERE (buyer_id IS NOT NULL);
CREATE INDEX idx_orders_cancelled_at ON public.orders USING btree (cancelled_at) WHERE (cancelled_at IS NOT NULL);
CREATE INDEX idx_orders_completed ON public.orders USING btree (buyer_id, created_at DESC) WHERE (status = 'completed'::text);
CREATE INDEX idx_orders_merchant_uid ON public.orders USING btree (merchant_uid);
CREATE INDEX idx_orders_number ON public.orders USING btree (order_number);
CREATE INDEX idx_orders_payment_id ON public.orders USING btree (payment_id);
CREATE INDEX idx_orders_payment_request_id ON public.orders USING btree (payment_request_id);
CREATE INDEX idx_orders_pending_payment ON public.orders USING btree (created_at DESC) WHERE (status = 'pending_payment'::text);
CREATE INDEX idx_orders_seller ON public.orders USING btree (seller_id);
CREATE INDEX idx_orders_seller_id ON public.orders USING btree (seller_id, created_at DESC);
CREATE INDEX idx_orders_seller_status ON public.orders USING btree (seller_id, status) WHERE (seller_id IS NOT NULL);
CREATE INDEX idx_orders_service_id ON public.orders USING btree (service_id);
CREATE INDEX idx_orders_status ON public.orders USING btree (status, payment_status);
CREATE UNIQUE INDEX orders_merchant_uid_key ON public.orders USING btree (merchant_uid);
CREATE UNIQUE INDEX orders_order_number_key ON public.orders USING btree (order_number);
CREATE INDEX orders_review_id_idx ON public.orders USING btree (review_id);
CREATE INDEX idx_page_views_created_at ON public.page_views USING btree (created_at DESC);
CREATE INDEX idx_page_views_device_type ON public.page_views USING btree (device_type);
CREATE INDEX idx_page_views_path ON public.page_views USING btree (path);
CREATE INDEX idx_page_views_session_id ON public.page_views USING btree (session_id);
CREATE INDEX idx_page_views_user_id ON public.page_views USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_payment_requests_buyer ON public.payment_requests USING btree (buyer_id);
CREATE INDEX idx_payment_requests_room ON public.payment_requests USING btree (room_id);
CREATE INDEX idx_payment_requests_seller ON public.payment_requests USING btree (seller_id);
CREATE INDEX idx_payment_requests_service_id ON public.payment_requests USING btree (service_id);
CREATE INDEX idx_payment_requests_status ON public.payment_requests USING btree (status);
CREATE INDEX idx_payments_order ON public.payments USING btree (order_id);
CREATE INDEX idx_payments_payment_id ON public.payments USING btree (payment_id);
CREATE INDEX idx_payments_status ON public.payments USING btree (status);
CREATE INDEX idx_portfolio_items_seller_id ON public.portfolio_items USING btree (seller_id);
CREATE INDEX idx_portfolio_items_visible ON public.portfolio_items USING btree (is_visible);
CREATE INDEX idx_portfolio_services_portfolio ON public.portfolio_services USING btree (portfolio_id);
CREATE INDEX idx_portfolio_services_service ON public.portfolio_services USING btree (service_id);
CREATE UNIQUE INDEX portfolio_services_portfolio_id_service_id_key ON public.portfolio_services USING btree (portfolio_id, service_id);
CREATE INDEX idx_premium_active ON public.premium_placements USING btree (is_active, start_date, end_date);
CREATE INDEX idx_premium_placements_campaign_id ON public.premium_placements USING btree (campaign_id);
CREATE INDEX idx_premium_placements_category_id ON public.premium_placements USING btree (category_id);
CREATE INDEX idx_premium_service ON public.premium_placements USING btree (service_id);
CREATE INDEX idx_profiles_role ON public.profiles USING btree (role);
CREATE INDEX idx_profiles_user_id ON public.profiles USING btree (user_id);
CREATE UNIQUE INDEX profiles_user_id_key ON public.profiles USING btree (user_id);
CREATE INDEX idx_quote_responses_quote_id ON public.quote_responses USING btree (quote_id);
CREATE INDEX idx_quote_responses_seller_id ON public.quote_responses USING btree (seller_id);
CREATE INDEX idx_quote_responses_status ON public.quote_responses USING btree (status);
CREATE INDEX idx_quotes_buyer_id ON public.quotes USING btree (buyer_id);
CREATE INDEX idx_quotes_category_id ON public.quotes USING btree (category_id);
CREATE INDEX idx_quotes_created_at ON public.quotes USING btree (created_at DESC);
CREATE INDEX idx_quotes_status ON public.quotes USING btree (status);
CREATE INDEX idx_refunds_approved_by ON public.refunds USING btree (approved_by);
CREATE INDEX idx_refunds_order ON public.refunds USING btree (order_id);
CREATE INDEX idx_refunds_payment ON public.refunds USING btree (payment_id);
CREATE INDEX idx_refunds_status ON public.refunds USING btree (status);
CREATE INDEX idx_reports_assigned_to ON public.reports USING btree (assigned_to);
CREATE INDEX idx_reports_reported_order_id ON public.reports USING btree (reported_order_id);
CREATE INDEX idx_reports_reported_review_id ON public.reports USING btree (reported_review_id);
CREATE INDEX idx_reports_reported_service_id ON public.reports USING btree (reported_service_id);
CREATE INDEX idx_reports_reported_user_id ON public.reports USING btree (reported_user_id);
CREATE INDEX idx_reports_reporter ON public.reports USING btree (reporter_id);
CREATE INDEX idx_reports_status ON public.reports USING btree (status, severity);
CREATE INDEX idx_reviews_buyer ON public.reviews USING btree (buyer_id);
CREATE INDEX idx_reviews_buyer_id ON public.reviews USING btree (buyer_id, created_at DESC);
CREATE INDEX idx_reviews_moderation ON public.reviews USING btree (created_at) WHERE ((moderated = true) OR (is_visible = false));
CREATE INDEX idx_reviews_order_id ON public.reviews USING btree (order_id);
CREATE INDEX idx_reviews_public ON public.reviews USING btree (created_at DESC) WHERE ((is_visible = true) AND (moderated = false));
CREATE INDEX idx_reviews_rating ON public.reviews USING btree (service_id, rating) WHERE ((is_visible = true) AND (moderated = false));
CREATE INDEX idx_reviews_seller ON public.reviews USING btree (seller_id);
CREATE INDEX idx_reviews_seller_id ON public.reviews USING btree (seller_id, created_at DESC);
CREATE INDEX idx_reviews_service ON public.reviews USING btree (service_id);
CREATE INDEX idx_reviews_service_id ON public.reviews USING btree (service_id, created_at DESC) WHERE ((is_visible = true) AND (moderated = false));
CREATE INDEX idx_reviews_visible ON public.reviews USING btree (is_visible, is_featured);
CREATE UNIQUE INDEX reviews_order_id_key ON public.reviews USING btree (order_id);
CREATE INDEX idx_revision_history_incomplete ON public.revision_history USING btree (order_id, completed_at) WHERE (completed_at IS NULL);
CREATE INDEX idx_revision_history_order_id ON public.revision_history USING btree (order_id);
CREATE INDEX idx_revision_history_requested_at ON public.revision_history USING btree (requested_at DESC);
CREATE INDEX idx_search_logs_category_id ON public.search_logs USING btree (category_id);
CREATE INDEX idx_search_logs_converted_service_id ON public.search_logs USING btree (converted_service_id);
CREATE INDEX idx_search_logs_keyword ON public.search_logs USING btree (keyword);
CREATE INDEX idx_search_logs_user ON public.search_logs USING btree (user_id);
CREATE INDEX idx_seller_earnings_seller_id ON public.seller_earnings USING btree (seller_id);
CREATE UNIQUE INDEX seller_earnings_seller_id_key ON public.seller_earnings USING btree (seller_id);
CREATE INDEX idx_seller_portfolio_category_id ON public.seller_portfolio USING btree (category_id);
CREATE INDEX idx_seller_portfolio_created_at ON public.seller_portfolio USING btree (created_at DESC);
CREATE INDEX idx_seller_portfolio_seller_id ON public.seller_portfolio USING btree (seller_id);
CREATE INDEX idx_seller_portfolio_service_id ON public.seller_portfolio USING btree (service_id);
CREATE INDEX idx_sellers_created_at ON public.sellers USING btree (created_at DESC);
CREATE INDEX idx_sellers_is_active ON public.sellers USING btree (is_active);
CREATE INDEX idx_sellers_is_verified ON public.sellers USING btree (is_verified);
CREATE INDEX idx_sellers_user_id ON public.sellers USING btree (user_id);
CREATE INDEX idx_sellers_verification_status ON public.sellers USING btree (verification_status);
CREATE UNIQUE INDEX sellers_user_id_key ON public.sellers USING btree (user_id);
CREATE INDEX idx_service_categories_service_id ON public.service_categories USING btree (service_id);
CREATE INDEX idx_service_favorites_created_at ON public.service_favorites USING btree (created_at DESC);
CREATE INDEX idx_service_favorites_service_id ON public.service_favorites USING btree (service_id);
CREATE INDEX idx_service_favorites_user_id ON public.service_favorites USING btree (user_id);
CREATE UNIQUE INDEX service_favorites_user_service_key ON public.service_favorites USING btree (user_id, service_id);
CREATE INDEX idx_service_packages_service_active ON public.service_packages USING btree (service_id, is_active, display_order);
CREATE UNIQUE INDEX idx_service_packages_unique_type ON public.service_packages USING btree (service_id, package_type) WHERE (is_active = true);
CREATE INDEX idx_service_revision_categories_category_id ON public.service_revision_categories USING btree (category_id);
CREATE INDEX idx_service_revision_categories_revision_id ON public.service_revision_categories USING btree (revision_id);
CREATE INDEX idx_service_revisions_seller_id ON public.service_revisions USING btree (seller_id);
CREATE INDEX idx_service_revisions_seller_status ON public.service_revisions USING btree (seller_id, status);
CREATE INDEX idx_service_revisions_service_id ON public.service_revisions USING btree (service_id);
CREATE INDEX idx_service_revisions_status ON public.service_revisions USING btree (status);
CREATE INDEX idx_service_view_logs_created_brin ON public.service_view_logs USING brin (created_at);
CREATE INDEX idx_service_view_logs_service_created ON public.service_view_logs USING btree (service_id, created_at DESC);
CREATE INDEX idx_service_view_logs_service_id ON public.service_view_logs USING btree (service_id);
CREATE INDEX idx_service_views_service_id ON public.service_views USING btree (service_id);
CREATE INDEX idx_service_views_user_id ON public.service_views USING btree (user_id);
CREATE INDEX idx_service_views_viewed_at ON public.service_views USING btree (viewed_at DESC);
CREATE UNIQUE INDEX service_views_user_service_key ON public.service_views USING btree (user_id, service_id);
CREATE INDEX idx_services_active ON public.services USING btree (created_at DESC) WHERE (status = 'active'::text);
CREATE INDEX idx_services_delivery_method ON public.services USING btree (delivery_method);
CREATE INDEX idx_services_has_packages ON public.services USING btree (has_packages) WHERE (has_packages = true);
CREATE INDEX idx_services_last_modified_by ON public.services USING btree (last_modified_by);
CREATE INDEX idx_services_location ON public.services USING btree (location_latitude, location_longitude) WHERE ((location_latitude IS NOT NULL) AND (location_longitude IS NOT NULL));
CREATE INDEX idx_services_popular ON public.services USING btree (views DESC) WHERE (status = 'active'::text);
CREATE INDEX idx_services_rating ON public.services USING btree (rating DESC, review_count DESC);
CREATE INDEX idx_services_seller_id ON public.services USING btree (seller_id);
CREATE INDEX idx_services_seller_status ON public.services USING btree (seller_id, status);
CREATE INDEX idx_services_slug ON public.services USING btree (slug);
CREATE INDEX idx_services_status ON public.services USING btree (status, deleted_at);
CREATE INDEX idx_services_status_active ON public.services USING btree (status) WHERE (status = 'active'::text);
CREATE INDEX idx_services_status_created ON public.services USING btree (status, created_at DESC) WHERE (status = 'active'::text);
CREATE INDEX idx_services_wishlist_count ON public.services USING btree (wishlist_count DESC);
CREATE UNIQUE INDEX services_slug_key ON public.services USING btree (slug);
CREATE INDEX idx_settlement_details_order_id ON public.settlement_details USING btree (order_id);
CREATE INDEX idx_settlement_details_settlement_id ON public.settlement_details USING btree (settlement_id);
CREATE INDEX idx_settlements_date ON public.settlements USING btree (settlement_date);
CREATE INDEX idx_settlements_seller ON public.settlements USING btree (seller_id);
CREATE INDEX idx_settlements_status ON public.settlements USING btree (status);
CREATE UNIQUE INDEX tags_name_key ON public.tags USING btree (name);
CREATE UNIQUE INDEX tags_slug_key ON public.tags USING btree (slug);
CREATE UNIQUE INDEX tax_invoices_invoice_number_key ON public.tax_invoices USING btree (invoice_number);
CREATE INDEX idx_user_wallets_user_id ON public.user_wallets USING btree (user_id);
CREATE UNIQUE INDEX user_wallets_user_id_key ON public.user_wallets USING btree (user_id);
CREATE INDEX idx_users_active ON public.users USING btree (is_active, deleted_at);
CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_is_active ON public.users USING btree (is_active);
CREATE INDEX idx_users_is_verified ON public.users USING btree (is_verified);
CREATE INDEX idx_users_verification_ci ON public.users USING btree (verification_ci);
CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);
CREATE INDEX idx_visitor_stats_daily_date ON public.visitor_stats_daily USING btree (date DESC);
CREATE INDEX idx_visitor_stats_daily_path ON public.visitor_stats_daily USING btree (path);
CREATE UNIQUE INDEX visitor_stats_daily_date_path_key ON public.visitor_stats_daily USING btree (date, path);
CREATE INDEX idx_visitor_stats_hourly_hour ON public.visitor_stats_hourly USING btree (hour DESC);
CREATE INDEX idx_visitor_stats_hourly_path ON public.visitor_stats_hourly USING btree (path);
CREATE UNIQUE INDEX visitor_stats_hourly_hour_path_key ON public.visitor_stats_hourly USING btree (hour, path);
CREATE INDEX idx_visitor_stats_monthly_path ON public.visitor_stats_monthly USING btree (path);
CREATE INDEX idx_visitor_stats_monthly_year_month ON public.visitor_stats_monthly USING btree (year DESC, month DESC);
CREATE UNIQUE INDEX visitor_stats_monthly_year_month_path_key ON public.visitor_stats_monthly USING btree (year, month, path);
CREATE INDEX idx_wallet_transactions_created_at ON public.wallet_transactions USING btree (created_at DESC);
CREATE INDEX idx_wallet_transactions_order_id ON public.wallet_transactions USING btree (order_id);
CREATE INDEX idx_wallet_transactions_user_id ON public.wallet_transactions USING btree (user_id);
CREATE INDEX idx_wallet_transactions_wallet_id ON public.wallet_transactions USING btree (wallet_id);
CREATE INDEX idx_withdrawal_requests_processed_by ON public.withdrawal_requests USING btree (processed_by);
CREATE INDEX idx_withdrawal_requests_seller_id ON public.withdrawal_requests USING btree (seller_id);
CREATE UNIQUE INDEX idx_withdrawal_requests_seller_pending ON public.withdrawal_requests USING btree (seller_id) WHERE (status = 'pending'::text);
CREATE INDEX idx_withdrawal_requests_status ON public.withdrawal_requests USING btree (status);
