-- 6. Triggers

CREATE TRIGGER update_campaigns_updated_at BEFORE UPDATE ON public.advertising_campaigns FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_advertising_credits_updated_at BEFORE UPDATE ON public.advertising_credits FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_advertising_payments_updated_at BEFORE UPDATE ON public.advertising_payments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_advertising_subscriptions_updated_at BEFORE UPDATE ON public.advertising_subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_buyers_updated_at BEFORE UPDATE ON public.buyers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_categories_updated_at BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_chat_room_last_message AFTER INSERT ON public.chat_messages FOR EACH ROW EXECUTE FUNCTION update_chat_room_last_message();
CREATE TRIGGER update_chat_room_last_message_trigger AFTER INSERT ON public.chat_messages FOR EACH ROW EXECUTE FUNCTION update_chat_room_last_message();
CREATE TRIGGER update_conversations_updated_at BEFORE UPDATE ON public.conversations FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_disputes_updated_at BEFORE UPDATE ON public.disputes FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trigger_update_errand_chat_messages_updated_at BEFORE UPDATE ON public.errand_chat_messages FOR EACH ROW EXECUTE FUNCTION update_errand_chat_messages_updated_at();
CREATE TRIGGER trigger_generate_food_order_number BEFORE INSERT ON public.food_orders FOR EACH ROW WHEN ((new.order_number IS NULL)) EXECUTE FUNCTION generate_food_order_number();
CREATE TRIGGER trigger_update_food_store_rating AFTER INSERT OR DELETE OR UPDATE ON public.food_reviews FOR EACH ROW EXECUTE FUNCTION update_food_store_rating();
CREATE TRIGGER trigger_notices_updated_at BEFORE UPDATE ON public.notices FOR EACH ROW EXECUTE FUNCTION update_notices_updated_at();
CREATE TRIGGER generate_order_number_trigger BEFORE INSERT ON public.orders FOR EACH ROW WHEN ((new.order_number IS NULL)) EXECUTE FUNCTION generate_order_number();
CREATE TRIGGER trigger_notify_new_order AFTER INSERT ON public.orders FOR EACH ROW EXECUTE FUNCTION notify_new_order();
CREATE TRIGGER trigger_notify_order_status_change AFTER UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION notify_order_status_change();
CREATE TRIGGER trigger_orders_insert AFTER INSERT ON public.orders FOR EACH ROW EXECUTE FUNCTION update_service_orders_count();
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_portfolio_items_updated_at BEFORE UPDATE ON public.portfolio_items FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_premium_updated_at BEFORE UPDATE ON public.premium_placements FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_quote_response_count_on_change AFTER INSERT OR DELETE ON public.quote_responses FOR EACH ROW EXECUTE FUNCTION update_quote_response_count();
CREATE TRIGGER update_quote_responses_updated_at BEFORE UPDATE ON public.quote_responses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_quotes_updated_at BEFORE UPDATE ON public.quotes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_reports_updated_at BEFORE UPDATE ON public.reports FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_reviews_updated_at BEFORE UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_seller_earnings_updated_at BEFORE UPDATE ON public.seller_earnings FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_sellers_updated_at BEFORE UPDATE ON public.sellers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trigger_service_favorites_delete AFTER DELETE ON public.service_favorites FOR EACH ROW EXECUTE FUNCTION update_service_wishlist_count();
CREATE TRIGGER trigger_service_favorites_insert AFTER INSERT ON public.service_favorites FOR EACH ROW EXECUTE FUNCTION update_service_wishlist_count();
CREATE TRIGGER trigger_increment_view_count AFTER INSERT ON public.service_view_logs FOR EACH ROW EXECUTE FUNCTION increment_service_view_count();
CREATE TRIGGER trigger_service_views_insert AFTER INSERT ON public.service_views FOR EACH ROW EXECUTE FUNCTION update_service_views_count();
CREATE TRIGGER generate_service_slug_trigger BEFORE INSERT OR UPDATE OF title ON public.services FOR EACH ROW EXECUTE FUNCTION generate_service_slug();
CREATE TRIGGER update_services_updated_at BEFORE UPDATE ON public.services FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_settlements_updated_at BEFORE UPDATE ON public.settlements FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_user_wallets_updated_at BEFORE UPDATE ON public.user_wallets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER create_wallet_on_user_creation AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION create_user_wallet();
CREATE TRIGGER trigger_create_seller_earnings AFTER INSERT OR UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION create_seller_earnings();
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION update_users_updated_at();
CREATE TRIGGER update_withdrawal_requests_updated_at BEFORE UPDATE ON public.withdrawal_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at();
